-- ALTER TABLE users ALTER COLUMN password TYPE varchar(100); -- Устанавливаем размер в 50. Проверим, укладываются ли в него наши данные!
-- INSERT INTO users(name, login, password) VALUES ('Nodir', 'admin', 'admin')
-- ALTER TABLE orders ADD COLUMN product_name varchar(100)
-- SELECT * FROM orderproducts
-- SELECT * FROM users
-- ALTER TABLE orders DROP COLUMN product_id
-- ALTER TABLE orders DROP COLUMN products
-- ALTER TABLE orderproducts ADD COLUMN product_count INTEGER;
-- SELECT * FROM users WHERE login
-- SELECT * FROM category WHERE category_name='фрукты'
-- SELECT o.order_id, o.user_id, o.totalcost, o.datatime, op.product_id, op.product_count
-- 								FROM orders o
-- 								JOIN orderproducts op ON o.order_id = op.order_id
-- 								WHERE o.user_id=7
SELECT * FROM product
-- SELECT o.order_id, o.user_id, o.totalcost, o.datatime, op.productid, op.product_count
--         FROM orders o
--         JOIN orderproducts op ON o.order_id = op.orderid